Add method for solve the movement problem at the switch mode
VDP-noclip/noclip pull request #121
Opened 2022-11-26 17:50 UTC by stefanofossati

The problem seems to be fixed:

- Add a method in the realitymovement script that is called when the switch from reality mode to noclip mode happend

2022-11-26 18:00 UTC, spig95 submitted a review, later dismissed
Methods name make it really clear, and it works!

2022-11-26 19:22 UTC, TizioMaurizio requested changes
I suggest to make it so that the reality body is unaffected by forces while in noclip mode to account for situations like this that would cause respawn loops, the player shouldn't move anyway in noclip
![Untitled](https://user-images.githubusercontent.com/48728364/204105698-c9e74098-7864-485a-b7f1-dde49f2fbaa0.png)

2022-11-26 19:22 UTC, TizioMaurizio commented on Assets/Code/Scripts/NoclipRealityManagement/RealityMovementCalibration.cs
> +
```suggestion
public void toggleKinematic(bool toggle)
    {
        _rigidbody.isKinematic = toggle;
    }
```

2022-11-26 19:23 UTC, TizioMaurizio commented on Assets/Code/Scripts/PlayerManagement/CameraManager.cs
> +            _realityMovement.ResetMovementAtSwitch();
```suggestion
            _realityMovement.toggleKinematic(isNoclipEnabled);
```

2022-11-26 19:24 UTC, TizioMaurizio commented on Assets/Code/Scripts/PlayerManagement/CameraManager.cs
>          {
```suggestion
        {
            _realityMovement.toggleKinematic(isNoclipEnabled);
```

2022-11-27 10:18 UTC, TizioMaurizio submitted a review, later dismissed

2022-11-27 10:35 UTC, TizioMaurizio approved these changes

2022-11-27 10:35 UTC, merged